<?php

namespace Modules\POS\Http\Controllers\Api\Cashier;

use App\Helpers\JsonResponse;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Resources;
use App\Http\Resources\NameResource;
use Modules\POS\Entities\Api\Cashier\Cashier;
use Modules\POS\Http\Requests\Api\Cashier\CashierRequest;
use Modules\POS\Repositories\IRepositories\Cashier\ICashierRepository;
use Modules\POS\Transformers\Api\Cashier\CashierResource;

use function getAutoGeneratedNextCode;

class CashierController extends Controller
{

    public function __construct(private ICashierRepository $cashierRepository)
    {
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     * @auth M.Mukhtar
     */
    public function index()
    {
        try {
            $cashiers = CashierResource::collection($this->cashierRepository->all());
            return $cashiers->additional(JsonResponse::success());
        } catch (\Exception $e) {
            return JsonResponse::respondError($e->getMessage());
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @auth M.Mukhtar
     */
    public function store(CashierRequest $request)
    {
        try {
            $model = $this->cashierRepository->create($request->validated());
            $cashier = new CashierResource($model);
            return $cashier->additional(JsonResponse::savedSuccessfully());
        } catch (\Exception $e) {
            return JsonResponse::respondError($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param Cashier $cashier
     * @return \Illuminate\Http\Response
     * @auth M.Mukhtar
     */
    public function show(Cashier $cashier)
    {
        try {
            $cashier = new CashierResource($cashier);
            return $cashier->additional(JsonResponse::success());
        } catch (\Exception $e) {
            return JsonResponse::respondError($e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param Cashier $cashier
     * @return \Illuminate\Http\Response
     * @auth M.Mukhtar
     */
    public function update(Cashier $cashier, CashierRequest $request)
    {
        try {
            $model = $this->cashierRepository->update($request->validated(), $cashier->id);
            return JsonResponse::respondSuccess(trans(JsonResponse::MSG_UPDATED_SUCCESSFULLY), null);
        } catch (\Exception $e) {
            return JsonResponse::respondError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Cashier $cashier
     * @return \Illuminate\Http\Response
     * @auth M.Mukhtar
     */
    public function destroy(Request $request)
    {
        try {
            $count = $this->cashierRepository->deleteRecords('pos_cashiers', $request['ids']);
            return $count > 1
            ? JsonResponse::respondError(trans("responses.msg_multi_resources_cannot_deleted"))
            : ($count == 1 ? JsonResponse::respondError(trans("responses.msg_cannot_deleted"))
            : JsonResponse::respondSuccess(trans(JsonResponse::MSG_DELETED_SUCCESSFULLY)));
        } catch(\Exception $e) {
            return JsonResponse::respondError($e->getMessage());
        }
    }


    /**
     * navigation.
     *
     * @param Cashier $cashier , case of navigation
     * @return object
     * @auth M.Mukhtar
     */
    public function navigate(Request $request, Cashier $cashier)
    {
        try {
            if (!in_array($request->case, ['previous', 'next', 'first', 'last']))
                return JsonResponse::respondError('The Navigate case should be one of previous,next,first,last', 422);
            $cashier = new CashierResource($this->cashierRepository->navigate($cashier->id, $request->case, 'type', $request->type));
            return $cashier->additional(JsonResponse::success());
        } catch (\Exception $e) {
            return JsonResponse::respondError($e->getMessage());
        }
    }

    public function getCode(Request $request)
    {
        try {
            return JsonResponse::respondSuccess('success', $this->cashierRepository->codeGenerator());
        } catch (\Exception $e) {
            return JsonResponse::respondError($e->getMessage());
        }

    }

    public function getNames()
    {
        try {
            $cashiers = NameResource::collection($this->cashierRepository->names());
            return $cashiers->additional(JsonResponse::success());
        } catch (\Exception $e) {
            return JsonResponse::respondError($e->getMessage());
        }
    }

    public function latestId()
    {
        try {
            return array_merge(['data' => ['id' => $this->cashierRepository->latestId()]], JsonResponse::success());
        } catch (\Exception $e) {
            return JsonResponse::respondError($e->getMessage());
        }
    }


}
